import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";
import Background from "./ui/background";
import Nav from "./ui/tap/nav/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="relative h-screen w-full overflow-hidden bg-black/70">
          <Background />
          {children}
          <div className="absolute bottom-0">
            <Nav />
          </div>
        </div>
      </body>
    </html>
  );
}
